export const mockSellers = [
  {
    id: '1',
    name: 'Ravi Kumar',
    skills: ['painting', 'wall_design'],
    rating: 4.8,
    location: 'Bangalore',
    followers: 156,
    isFollowing: true,
    phoneNumber: '919876543210',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    skills: ['plumbing', 'electrical'],
    rating: 4.6,
    location: 'Delhi',
    followers: 89,
    isFollowing: false,
    phoneNumber: '919876543211',
  },
  {
    id: '3',
    name: 'Anil Patel',
    skills: ['carpentry', 'furniture'],
    rating: 4.9,
    location: 'Mumbai',
    followers: 203,
    isFollowing: true,
    phoneNumber: '919876543212',
  },
  {
    id: '4',
    name: 'Lakshmi Reddy',
    skills: ['bamboo_work', 'crafts'],
    rating: 4.7,
    location: 'Hyderabad',
    followers: 134,
    isFollowing: false,
    phoneNumber: '919876543213',
  },
  {
    id: '5',
    name: 'Suresh Gowda',
    skills: ['electrical', 'appliance_repair'],
    rating: 4.5,
    location: 'Bangalore',
    followers: 67,
    isFollowing: false,
    phoneNumber: '919876543214',
  },
  {
    id: '6',
    name: 'Meera Singh',
    skills: ['painting', 'interior_design'],
    rating: 4.8,
    location: 'Pune',
    followers: 178,
    isFollowing: true,
    phoneNumber: '919876543215',
  },
  {
    id: '7',
    name: 'Rajesh Kumar',
    skills: ['plumbing', 'waterproofing'],
    rating: 4.4,
    location: 'Chennai',
    followers: 92,
    isFollowing: false,
    phoneNumber: '919876543216',
  },
  {
    id: '8',
    name: 'Anjali Gupta',
    skills: ['carpentry', 'woodwork'],
    rating: 4.9,
    location: 'Jaipur',
    followers: 156,
    isFollowing: true,
    phoneNumber: '919876543217',
  },
  {
    id: '9',
    name: 'Vikram Yadav',
    skills: ['masonry', 'construction'],
    rating: 4.6,
    location: 'Lucknow',
    followers: 84,
    isFollowing: false,
    phoneNumber: '919876543218',
  },
  {
    id: '10',
    name: 'Sunita Devi',
    skills: ['bamboo_work', 'handicrafts'],
    rating: 4.7,
    location: 'Bhopal',
    followers: 119,
    isFollowing: false,
    phoneNumber: '919876543219',
  },
];

export const mockJobs = [
  {
    id: '1',
    title: 'Living Room Paint Job',
    description: 'Need to paint living room and bedroom walls with quality paint. Includes wall preparation and primer.',
    skill: 'painting',
    budget: '₹15,000',
    timeline: '3 days',
    location: 'Koramangala, Bangalore',
    postedBy: 'Amit Sharma',
    postedAt: '2 hours ago',
  },
  {
    id: '2',
    title: 'Kitchen Plumbing Repair',
    description: 'Fix leaking pipes and install new faucet in kitchen. Emergency repair needed.',
    skill: 'plumbing',
    budget: '₹8,000',
    timeline: '1 day',
    location: 'Whitefield, Bangalore',
    postedBy: 'Priya Singh',
    postedAt: '4 hours ago',
  },
  {
    id: '3',
    title: 'Custom Wooden Furniture',
    description: 'Design and build custom dining table and chairs for 6 people.',
    skill: 'carpentry',
    budget: '₹35,000',
    timeline: '2 weeks',
    location: 'Indiranagar, Bangalore',
    postedBy: 'Rohit Gupta',
    postedAt: '1 day ago',
  },
  {
    id: '4',
    title: 'Bamboo Garden Structure',
    description: 'Create decorative bamboo structure for garden area with seating arrangement.',
    skill: 'bamboo_work',
    budget: '₹20,000',
    timeline: '1 week',
    location: 'HSR Layout, Bangalore',
    postedBy: 'Maya Patel',
    postedAt: '1 day ago',
  },
  {
    id: '5',
    title: 'House Electrical Wiring',
    description: 'Complete electrical wiring for 2BHK apartment including switches and outlets.',
    skill: 'electrical',
    budget: '₹25,000',
    timeline: '5 days',
    location: 'Electronic City, Bangalore',
    postedBy: 'Suresh Kumar',
    postedAt: '2 days ago',
  },
];

export const mockServices = [
  {
    id: '1',
    title: 'Interior Wall Painting',
    description: 'Professional interior painting with premium quality paints and finish.',
    price: 'Starting ₹50/sq ft',
    category: 'Painting',
  },
  {
    id: '2',
    title: 'Custom Wall Designs',
    description: 'Creative wall designs including texture painting and artistic patterns.',
    price: 'Starting ₹200/sq ft',
    category: 'Painting',
  },
  {
    id: '3',
    title: 'Color Consultation',
    description: 'Professional color consultation for your home interior design.',
    price: '₹2,000 per consultation',
    category: 'Design',
  },
];